//! Tests for function translation error cases.
//!
//! Verifies that PostgreSQL-specific functions that have no direct SQLite
//! equivalent produce clear, actionable error messages rather than silently
//! producing incorrect SQL.

use pg2sqlite::prelude::{Pg2Sqlite, Pg2SqliteOptions};

// ---------------------------------------------------------------------------
// ts_rank / ts_rank_cd
// ---------------------------------------------------------------------------

/// `ts_rank` has no direct SQLite equivalent.  The translator should fail
/// with a message that directs the user to FTS5's `bm25()`.
#[test]
fn test_ts_rank_causes_error() {
    let sql = "
        CREATE TABLE documents (id INTEGER PRIMARY KEY, content TEXT);
        SELECT ts_rank(content, 'query') FROM documents;
    ";
    let result = Pg2Sqlite::default().sql(sql).unwrap().translate(&Pg2SqliteOptions::default());

    assert!(result.is_err(), "ts_rank should produce a translation error");
    let error_msg = result.unwrap_err().to_string();
    assert!(
        error_msg.contains("bm25"),
        "Error should mention 'bm25' as the FTS5 alternative, got: {error_msg}"
    );
}

/// `ts_rank_cd` is subject to the same restriction as `ts_rank`.
#[test]
fn test_ts_rank_cd_causes_error() {
    let sql = "
        CREATE TABLE documents (id INTEGER PRIMARY KEY, content TEXT);
        SELECT ts_rank_cd(content, 'query') FROM documents;
    ";
    let result = Pg2Sqlite::default().sql(sql).unwrap().translate(&Pg2SqliteOptions::default());

    assert!(result.is_err(), "ts_rank_cd should produce a translation error");
    let error_msg = result.unwrap_err().to_string();
    assert!(
        error_msg.contains("bm25"),
        "Error should mention 'bm25' as the FTS5 alternative, got: {error_msg}"
    );
}

// ---------------------------------------------------------------------------
// GENERATED BY DEFAULT AS IDENTITY
// ---------------------------------------------------------------------------

/// SQLite does not support `GENERATED BY DEFAULT AS IDENTITY`.  The translator
/// should return an explicit error rather than emitting invalid SQLite DDL.
#[test]
fn test_generated_by_default_as_identity_causes_error() {
    // PostgreSQL identity column with BY DEFAULT semantics
    let sql = "CREATE TABLE t (id INTEGER GENERATED BY DEFAULT AS IDENTITY, name TEXT NOT NULL);";
    let result = Pg2Sqlite::default().sql(sql).unwrap().translate(&Pg2SqliteOptions::default());

    assert!(result.is_err(), "GENERATED BY DEFAULT AS IDENTITY should produce a translation error");
    let error_msg = result.unwrap_err().to_string();
    assert!(
        error_msg.to_lowercase().contains("generated"),
        "Error should mention GENERATED, got: {error_msg}"
    );
}
