//! Temporal semantic fidelity tests measuring the six findings from the
//! TemporalSemantics scout. Each test executes the crate's emitted SQL against
//! an in-memory SQLite and compares against the PostgreSQL reference value
//! measured in Docker under `SET TIME ZONE 'UTC'`.
//!
//! rusqlite is used here because the SQL is dynamically generated by the
//! translator at test runtime; Diesel's typed DSL requires a schema known at
//! compile time and cannot execute an arbitrary translated SQL string.

use pg2sqlite::prelude::{Pg2Sqlite, Pg2SqliteOptions};

#[path = "helpers/run_translated.rs"]
mod run_translated_helper;

use run_translated_helper::run_translated_with;

fn translate_err(pg: &str) -> String {
    Pg2Sqlite::default()
        .sql(pg)
        .unwrap()
        .translate_to_sql(&Pg2SqliteOptions::default())
        .expect_err("expected a translation refusal")
        .to_string()
}

// ── Finding 1: TIMESTAMPTZ minute-less offsets (±HH → ±HH:MM) ─────────────
//
// PostgreSQL accepts '+02' offsets; SQLite date functions return NULL for them.
// The fix normalises literals in INSERT positions and CAST/TypedString forms.
// PostgreSQL reference (UTC session): epoch of '2024-01-15 10:30:45.123456+02'
// = '2024-01-15 08:30:45.123456+00' = 1705307445.123456 (ms: .123).

const TSTZ_DDL: &str = "CREATE TABLE t (id INTEGER PRIMARY KEY, tsz TIMESTAMPTZ);";

/// INSERT literal '...+02' is normalised to '...+02:00' so epoch is non-NULL.
#[test]
fn timestamptz_insert_offset_without_minutes_is_normalised() {
    let script = format!(
        "{TSTZ_DDL}\n\
         INSERT INTO t VALUES (1, '2024-01-15 10:30:45.123456+02');\n\
         SELECT EXTRACT(EPOCH FROM tsz) FROM t WHERE id = 1;"
    );
    let result = run_translated_with(&script, &Pg2SqliteOptions::default())
        .remove(0)
        .expect("EXTRACT(EPOCH) must not be NULL after offset normalisation");
    // 1705307445 seconds; allow ±2 for float rendering
    let epoch: f64 = result.parse().expect("epoch must be numeric");
    assert!((epoch - 1_705_307_445.0).abs() < 2.0, "epoch should be ~1705307445, got {epoch}");
}

/// TypedString 'timestamptz ...' normalises the offset.
#[test]
fn timestamptz_typed_string_offset_without_minutes_is_normalised() {
    let result = run_translated_with(
        "SELECT EXTRACT(EPOCH FROM timestamptz '2024-01-15 10:30:45.123456+02');",
        &Pg2SqliteOptions::default(),
    )
    .remove(0)
    .expect("EXTRACT(EPOCH) must not be NULL for typed-string timestamptz");
    let epoch: f64 = result.parse().expect("epoch must be numeric");
    assert!((epoch - 1_705_307_445.0).abs() < 2.0, "epoch should be ~1705307445, got {epoch}");
}

/// CAST literal also normalises the offset.
#[test]
fn timestamptz_cast_offset_without_minutes_is_normalised() {
    let result = run_translated_with(
        "SELECT EXTRACT(EPOCH FROM CAST('2024-01-15 10:30:45.123456+02' AS TIMESTAMPTZ));",
        &Pg2SqliteOptions::default(),
    )
    .remove(0)
    .expect("EXTRACT(EPOCH) must not be NULL for CAST timestamptz");
    let epoch: f64 = result.parse().expect("epoch must be numeric");
    assert!((epoch - 1_705_307_445.0).abs() < 2.0, "epoch should be ~1705307445, got {epoch}");
}

/// '+02:00' and 'Z' offsets are already valid and must not be mangled.
#[test]
fn timestamptz_valid_offsets_pass_through_unchanged() {
    // '+02:00': epoch must still be 1705307445
    let r1 = run_translated_with(
        "SELECT EXTRACT(EPOCH FROM timestamptz '2024-01-15 10:30:45.123456+02:00');",
        &Pg2SqliteOptions::default(),
    )
    .remove(0)
    .expect("'+02:00' offset must work");
    let e1: f64 = r1.parse().unwrap();
    assert!((e1 - 1_705_307_445.0).abs() < 2.0, "got {e1}");

    // '+00' also gets :00 appended, epoch is 10:30:45 UTC = 1705314645
    let r2 = run_translated_with(
        "SELECT EXTRACT(EPOCH FROM timestamptz '2024-01-15 10:30:45+00');",
        &Pg2SqliteOptions::default(),
    )
    .remove(0)
    .expect("'+00' offset must work after normalisation");
    let e2: f64 = r2.parse().unwrap();
    assert!((e2 - 1_705_314_645.0).abs() < 2.0, "got {e2}");
}

// ── Finding 2: interval arithmetic sub-second precision ────────────────────
//
// Without 'subsec', datetime() truncates to whole seconds. PostgreSQL keeps
// microseconds; SQLite keeps milliseconds (inherent limit). The fix adds
// 'subsec' to every interval datetime() call.
// PostgreSQL reference (UTC session):
//   timestamp '2024-01-15 10:30:45.123456' + interval '1 month'
//   = 2024-02-15 10:30:45.123456   (SQLite: .123, inherent ms limit)

/// Sub-second fraction is preserved in timestamp + interval results.
#[test]
fn interval_arithmetic_preserves_subsecond_precision() {
    let result = run_translated_with(
        "SELECT timestamp '2024-01-15 10:30:45.123456' + interval '1 month';",
        &Pg2SqliteOptions::default(),
    )
    .remove(0)
    .expect("result must not be NULL");
    // Must have a decimal point — whole seconds would be "2024-02-15 10:30:45"
    assert!(result.contains('.'), "sub-second fraction must be present, got '{result}'");
    assert!(result.starts_with("2024-02-15 10:30:45.12"), "wrong datetime, got '{result}'");
}

/// Sub-second fraction is preserved in timestamp - interval results.
#[test]
fn interval_subtraction_preserves_subsecond_precision() {
    let result = run_translated_with(
        "SELECT timestamp '2024-02-15 10:30:45.123456' - interval '1 month';",
        &Pg2SqliteOptions::default(),
    )
    .remove(0)
    .expect("result must not be NULL");
    assert!(result.contains('.'), "sub-second fraction missing, got '{result}'");
    assert!(result.starts_with("2024-01-15 10:30:45.12"), "wrong datetime, got '{result}'");
}

/// 'floor' month-end clamp still works alongside 'subsec'.
/// PostgreSQL: timestamp '2024-01-31 10:30:45.123456' + interval '1 month'
///           = 2024-02-29 10:30:45.123456  (leap year)
#[test]
fn interval_floor_clamp_with_subsec() {
    let result = run_translated_with(
        "SELECT timestamp '2024-01-31 10:30:45.123456' + interval '1 month';",
        &Pg2SqliteOptions::default(),
    )
    .remove(0)
    .expect("result must not be NULL");
    assert!(result.starts_with("2024-02-29 10:30:45.12"), "got '{result}'");
}

/// n * INTERVAL path also carries 'subsec'.
#[test]
fn scaled_interval_preserves_subsecond_precision() {
    let result = run_translated_with(
        "SELECT timestamp '2024-01-15 10:30:45.123456' + 2 * interval '1 month';",
        &Pg2SqliteOptions::default(),
    )
    .remove(0)
    .expect("result must not be NULL");
    assert!(result.contains('.'), "sub-second fraction missing, got '{result}'");
    assert!(result.starts_with("2024-03-15 10:30:45.12"), "got '{result}'");
}

// ── Finding 3: DATE vs TIMESTAMP comparison ─────────────────────────────────
//
// PostgreSQL implicitly casts DATE to midnight TIMESTAMP for comparisons;
// SQLite compares text and 'YYYY-MM-DD' ≠ 'YYYY-MM-DD HH:MM:SS'.
// The fix wraps the DATE side with strftime('%Y-%m-%d 00:00:00', d).
// PostgreSQL reference (UTC session, SET TIME ZONE 'UTC'):
//   COUNT(*) WHERE ts = d → 1 (midnight row matches its date)

const DT_DDL: &str = "CREATE TABLE t (id INTEGER PRIMARY KEY, ts TIMESTAMP, d DATE);";

/// WHERE ts = d returns midnight timestamp rows (not zero).
#[test]
fn date_equals_midnight_timestamp() {
    let script = format!(
        "{DT_DDL}\n\
         INSERT INTO t VALUES \
           (1, '2024-12-31 00:00:00', '2024-12-31'),\
           (2, '2024-12-31 12:00:00', '2024-12-31');\n\
         SELECT COUNT(*) FROM t WHERE ts = d;"
    );
    let count: i64 = run_translated_with(&script, &Pg2SqliteOptions::default())
        .remove(0)
        .expect("COUNT must not be NULL")
        .parse()
        .expect("COUNT must be integer");
    // PG: 1 (only midnight row); our fix must also answer 1
    assert_eq!(count, 1, "midnight timestamp must match its date");
}

/// WHERE ts >= d AND ts <= d matches midnight rows.
#[test]
fn date_range_comparison_matches_midnight_timestamp() {
    let script = format!(
        "{DT_DDL}\n\
         INSERT INTO t VALUES \
           (1, '2024-12-31 00:00:00', '2024-12-31'),\
           (2, '2024-12-31 12:00:00', '2024-12-31');\n\
         SELECT COUNT(*) FROM t WHERE ts >= d AND ts <= d;"
    );
    let count: i64 = run_translated_with(&script, &Pg2SqliteOptions::default())
        .remove(0)
        .expect("COUNT must not be NULL")
        .parse()
        .expect("COUNT must be integer");
    assert_eq!(count, 1, "midnight timestamp must match bounded date range");
}

/// CAST(d AS TIMESTAMP) promotes the date to midnight for comparison.
#[test]
fn cast_date_to_timestamp_adds_midnight() {
    let result = run_translated_with(
        "SELECT CAST(date '2024-12-31' AS TIMESTAMP);",
        &Pg2SqliteOptions::default(),
    )
    .remove(0)
    .expect("CAST(date AS TIMESTAMP) must not be NULL");
    assert_eq!(result, "2024-12-31 00:00:00", "date cast to timestamp must be midnight");
}

// ── Finding 4: TIMESTAMPTZ cross-offset equality (documented limitation) ───
//
// Equality and ordering across different offsets (+02:00 vs +00:00) compare
// text, not instants. This is unfixable without changing the storage model.
// The LossyDowngrade warning now names this consequence.
// Test: verify the warning IS emitted for a TIMESTAMPTZ column.

/// The LossyDowngrade warning for TIMESTAMPTZ mentions comparison semantics.
#[test]
fn timestamptz_column_emits_lossy_downgrade_warning() {
    use pg2sqlite::warnings::TranslationWarning;
    let report = Pg2Sqlite::default()
        .sql("CREATE TABLE t (id INTEGER PRIMARY KEY, tsz TIMESTAMPTZ);")
        .unwrap()
        .translate_with_report(&Pg2SqliteOptions::default())
        .expect("should translate");
    let has_tz_warning = report.warnings.iter().any(|w| {
        matches!(w, TranslationWarning::LossyDowngrade { construct, reason, .. }
            if construct == "WITH TIME ZONE" && reason.contains("text"))
    });
    assert!(has_tz_warning, "expected LossyDowngrade for WITH TIME ZONE: {:?}", report.warnings);
}

// ── Finding 5: Leap-second TIME literal ────────────────────────────────────
//
// PostgreSQL normalises time '23:59:60' to 24:00:00; SQLite cannot represent
// that boundary. The fix refuses the literal at translation time.

/// time '23:59:60' TypedString form is refused.
#[test]
fn leap_second_typed_string_is_refused() {
    let err = translate_err("SELECT time '23:59:60';");
    assert!(
        err.contains("leap second") || err.contains("second=60"),
        "refusal must mention leap second, got: {err}"
    );
}

/// CAST('23:59:60' AS TIME) is refused.
#[test]
fn leap_second_cast_is_refused() {
    let err = translate_err("SELECT CAST('23:59:60' AS TIME);");
    assert!(
        err.contains("leap second") || err.contains("second=60"),
        "refusal must mention leap second, got: {err}"
    );
}

/// Normal times (including second=59) are not refused.
#[test]
fn normal_time_literals_are_accepted() {
    let r = run_translated_with("SELECT time '23:59:59';", &Pg2SqliteOptions::default());
    assert!(!r.is_empty(), "normal time literal must translate and execute");

    let r2 = run_translated_with("SELECT CAST('12:30:45' AS TIME);", &Pg2SqliteOptions::default());
    assert!(!r2.is_empty(), "CAST time literal must translate and execute");
}

// ── Finding 6: epoch functions render UTC only (documented limitation) ─────
//
// to_timestamp(epoch) and now() render in UTC on the SQLite side. This matches
// a UTC PostgreSQL session but diverges for non-UTC sessions. SQLite has no
// session zone; the UTC assumption is inherent and cannot be fixed.
// Test: to_timestamp(0) returns the Unix epoch in UTC (matches PG UTC session).

/// to_timestamp(0) returns the Unix epoch string, matching a UTC PG session.
#[test]
fn to_timestamp_zero_matches_utc_epoch() {
    let result = run_translated_with("SELECT to_timestamp(0);", &Pg2SqliteOptions::default())
        .remove(0)
        .expect("to_timestamp(0) must not be NULL");
    assert_eq!(result, "1970-01-01 00:00:00", "to_timestamp(0) must be Unix epoch in UTC");
}

// ── INSERT ... SELECT into TIMESTAMPTZ column (for_each_insert_position Select
// branch) ──

/// INSERT ... SELECT at a TIMESTAMPTZ-column position normalises the offset
/// just as VALUES does; exercises SetExpr::Select in for_each_insert_position.
#[test]
fn timestamptz_insert_select_normalises_offset() {
    let result = run_translated_with(
        "CREATE TABLE t (id INTEGER PRIMARY KEY, tsz TIMESTAMPTZ);
         INSERT INTO t (id, tsz) SELECT 1, '2024-01-15 10:30:45+02';
         SELECT EXTRACT(EPOCH FROM tsz) FROM t WHERE id = 1;",
        &Pg2SqliteOptions::default(),
    )
    .remove(0)
    .expect("EXTRACT(EPOCH) must not be NULL after offset normalisation via SELECT");
    // 2024-01-15 10:30:45 UTC+2 = 08:30:45 UTC = 1705307445. Measured.
    let epoch: f64 = result.parse().expect("epoch must be numeric");
    assert!((epoch - 1_705_307_445.0).abs() < 2.0, "epoch should be ~1705307445, got {epoch}");
}

// ── DATE compared with TIMESTAMP promotes the date side (expr.rs 2276-2288) ──

/// `date_col < timestamp_col` must promote the date to midnight so the text
/// representations compare correctly. Date on left, Timestamp on right.
#[test]
fn date_column_less_than_timestamp_column_promotes_date() {
    let rows = run_translated_with(
        "CREATE TABLE t (d DATE NOT NULL, ts TIMESTAMP NOT NULL);
         INSERT INTO t VALUES ('2024-01-15', '2024-01-15 00:00:01');
         SELECT CASE WHEN d < ts THEN 'yes' ELSE 'no' END FROM t;",
        &Pg2SqliteOptions::default(),
    );
    // date '2024-01-15' at midnight is before timestamp '2024-01-15 00:00:01'.
    assert_eq!(rows, vec![Some("yes".to_string())]);
}

/// `timestamp_col < date_col` covers the rk=Date branch (right side promoted).
#[test]
fn timestamp_column_less_than_date_column_promotes_date_rhs() {
    let rows = run_translated_with(
        "CREATE TABLE t (d DATE NOT NULL, ts TIMESTAMP NOT NULL);
         INSERT INTO t VALUES ('2024-01-15', '2024-01-14 23:59:59');
         SELECT CASE WHEN ts < d THEN 'yes' ELSE 'no' END FROM t;",
        &Pg2SqliteOptions::default(),
    );
    // timestamp '2024-01-14 23:59:59' is before date '2024-01-15' at midnight.
    assert_eq!(rows, vec![Some("yes".to_string())]);
}

// ── CAST(date AS TIMESTAMP) adds midnight (expr.rs 2530) ─────────────────────

/// `CAST(d AS TIMESTAMP)` must produce a TIMESTAMP at midnight so it is
/// stored in a form comparable with other TIMESTAMP values.
#[test]
fn cast_date_column_to_timestamp_adds_midnight() {
    let rows = run_translated_with(
        "CREATE TABLE t (d DATE NOT NULL);
         INSERT INTO t VALUES ('2024-01-15');
         SELECT CAST(d AS TIMESTAMP) FROM t;",
        &Pg2SqliteOptions::default(),
    );
    let val = rows.into_iter().next().expect("one row").expect("non-null");
    assert!(val.contains("2024-01-15"), "must contain the date: {val}");
    assert!(val.contains("00:00:00"), "must have midnight time added: {val}");
}

// ── CAST(literal AS TIMESTAMP WITH TIME ZONE) normalises offset (expr.rs 2550)
// ──

/// The `data_type.translate_with_warnings` at line 2550 inside the CAST
/// TIMESTAMPTZ branch runs even when the data type is spelled out in full.
#[test]
fn cast_string_with_bare_offset_to_timestamp_with_time_zone_normalises() {
    let result = run_translated_with(
        "SELECT EXTRACT(EPOCH FROM CAST('2024-01-15 10:30:45+03' AS TIMESTAMP WITH TIME ZONE));",
        &Pg2SqliteOptions::default(),
    )
    .remove(0)
    .expect("epoch must not be NULL");
    // 2024-01-15 10:30:45 UTC+3 = 07:30:45 UTC = 1705303845. Measured.
    let epoch: f64 = result.parse().expect("epoch must be numeric");
    assert!((epoch - 1_705_303_845.0).abs() < 2.0, "epoch should be ~1705303845, got {epoch}");
}
