//! Focused tests for DDL clause gap fixes: ALTER TABLE RENAME, GENERATED AS
//! IDENTITY, CREATE UNLOGGED TABLE, and LIKE/INHERITS/PARTITION OF rejects.
//!
//! These tests assert observable contracts (exact emitted SQL or error message
//! content) rather than implementation internals.

use pg2sqlite::{
    prelude::{Pg2Sqlite, Pg2SqliteOptions},
    warnings::TranslationWarning,
};
use rusqlite::Connection;

fn opts() -> Pg2SqliteOptions {
    Pg2SqliteOptions::default()
}

/// Translates `sql` with the given options and returns the string vec.
fn translate(sql: &str) -> Result<Vec<String>, pg2sqlite::errors::Error> {
    Pg2Sqlite::default().sql(sql)?.translate_to_sql(&opts())
}

/// Translates `sql` and collects warnings alongside the string vec.
fn translate_with_warnings(
    sql: &str,
) -> Result<(Vec<String>, Vec<TranslationWarning>), pg2sqlite::errors::Error> {
    let report = Pg2Sqlite::default().sql(sql)?.translate_with_report(&opts())?;
    let stmts = report.statements.iter().map(|s| s.to_string()).collect();
    Ok((stmts, report.warnings))
}

/// Executes every statement in `stmts` through rusqlite to confirm they parse
/// and run without error.
///
/// # Errors
///
/// Returns the first SQLite error encountered.
fn sqlite_accepts(stmts: &[String]) -> Result<(), rusqlite::Error> {
    let conn = Connection::open_in_memory()?;
    for s in stmts {
        conn.execute_batch(s)?;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// ALTER TABLE RENAME TO
// ---------------------------------------------------------------------------

/// Before the fix this panicked inside sql-traits schema construction, which is
/// a public-API defect. After the fix it must return Ok and the emitted SQL
/// must be valid SQLite.
#[test]
fn rename_no_longer_panics() {
    let setup = "CREATE TABLE t (id INT PRIMARY KEY);";
    let rename = "ALTER TABLE t RENAME TO t2;";
    let full = format!("{setup}\n{rename}");

    // Must not panic.
    let result = std::panic::catch_unwind(|| translate(&full));
    let stmts = result.expect("translate must not panic").expect("translate must succeed");

    // The last statement must be the rename, and it must run without error.
    let rename_stmt = stmts.last().expect("at least one statement emitted");
    assert!(
        rename_stmt.to_uppercase().contains("RENAME"),
        "expected RENAME in emitted statement, got: {rename_stmt}"
    );

    // Build a fresh db with the original table, then apply the rename.
    let conn = Connection::open_in_memory().unwrap();
    conn.execute_batch("CREATE TABLE t (id INTEGER PRIMARY KEY NOT NULL) STRICT;").unwrap();
    conn.execute_batch(rename_stmt).unwrap();
}

// ---------------------------------------------------------------------------
// GENERATED AS IDENTITY on an integer primary key
// ---------------------------------------------------------------------------

/// GENERATED ALWAYS AS IDENTITY on INTEGER PRIMARY KEY must produce the same
/// output as the equivalent SERIAL column, because SQLite's INTEGER PRIMARY KEY
/// is a rowid alias that already auto-assigns.
#[test]
fn identity_always_pk_equals_serial() {
    let identity_sql = "CREATE TABLE a (id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY);";
    let serial_sql = "CREATE TABLE a (id SERIAL PRIMARY KEY);";

    let identity_out = translate(identity_sql).expect("identity should translate");
    let serial_out = translate(serial_sql).expect("serial should translate");

    assert_eq!(
        identity_out, serial_out,
        "GENERATED ALWAYS AS IDENTITY on INTEGER PRIMARY KEY must match SERIAL output"
    );

    sqlite_accepts(&identity_out).expect("emitted SQL must be valid SQLite");
}

/// GENERATED BY DEFAULT AS IDENTITY on INTEGER PRIMARY KEY must also succeed
/// and match the SERIAL output.
#[test]
fn identity_by_default_pk_equals_serial() {
    let identity_sql = "CREATE TABLE a (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);";
    let serial_sql = "CREATE TABLE a (id SERIAL PRIMARY KEY);";

    let identity_out = translate(identity_sql).expect("identity should translate");
    let serial_out = translate(serial_sql).expect("serial should translate");

    assert_eq!(
        identity_out, serial_out,
        "GENERATED BY DEFAULT AS IDENTITY on INTEGER PRIMARY KEY must match SERIAL output"
    );
}

/// An integer primary key translated from an IDENTITY column must actually
/// auto-assign when a row is inserted without providing that column.
#[test]
fn identity_pk_auto_assigns_on_insert() {
    let sql = "CREATE TABLE a (id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY);";
    let stmts = translate(sql).expect("should translate");
    sqlite_accepts(&stmts).expect("DDL must be valid");

    let conn = Connection::open_in_memory().unwrap();
    for s in &stmts {
        conn.execute_batch(s).unwrap();
    }
    conn.execute_batch("INSERT INTO a DEFAULT VALUES;").unwrap();
    let id: i64 = conn.query_row("SELECT id FROM a", [], |row| row.get(0)).unwrap();
    assert_ne!(id, 0, "auto-assigned rowid must be nonzero");
}

/// GENERATED AS IDENTITY on a non-integer-primary-key column must be rejected.
/// SQLite can only auto-assign the rowid (INTEGER PRIMARY KEY).
#[test]
fn identity_non_pk_is_rejected() {
    let sql = "CREATE TABLE a (id INT, x INT GENERATED ALWAYS AS IDENTITY);";
    let err = translate(sql).expect_err("non-PK IDENTITY must be an error");
    let msg = err.to_string();
    assert!(
        msg.contains("IDENTITY") || msg.contains("identity") || msg.contains("INTEGER PRIMARY KEY"),
        "error must name the construct and why it fails: {msg}"
    );
}

/// GENERATED BY DEFAULT AS IDENTITY on a non-PK column must also be rejected.
#[test]
fn identity_by_default_non_pk_is_rejected() {
    let sql = "CREATE TABLE a (id INT PRIMARY KEY, x INT GENERATED BY DEFAULT AS IDENTITY);";
    let err = translate(sql).expect_err("non-PK BY DEFAULT IDENTITY must be an error");
    let msg = err.to_string();
    assert!(
        msg.contains("IDENTITY") || msg.contains("identity") || msg.contains("INTEGER PRIMARY KEY"),
        "error must name the construct and why it fails: {msg}"
    );
}

// ---------------------------------------------------------------------------
// CREATE UNLOGGED TABLE
// ---------------------------------------------------------------------------

/// UNLOGGED must be stripped and the table must be emitted as a normal table.
/// A LossyDrop warning must be emitted.
#[test]
fn unlogged_drops_modifier_and_warns() {
    let sql = "CREATE UNLOGGED TABLE a (id INT PRIMARY KEY);";
    let (stmts, warnings) = translate_with_warnings(sql).expect("UNLOGGED should translate");

    // The emitted SQL must not contain UNLOGGED.
    for s in &stmts {
        assert!(
            !s.to_uppercase().contains("UNLOGGED"),
            "emitted SQL must not contain UNLOGGED: {s}"
        );
    }

    // The table must be valid SQLite.
    sqlite_accepts(&stmts).expect("emitted SQL must be valid SQLite");

    // A LossyDrop warning must have been emitted for the UNLOGGED modifier.
    let has_warning = warnings.iter().any(|w| {
        matches!(w, TranslationWarning::LossyDrop { construct, .. } if *construct == "UNLOGGED")
    });
    assert!(has_warning, "expected a LossyDrop warning for UNLOGGED, got: {warnings:?}");
}

// ---------------------------------------------------------------------------
// CREATE TABLE (LIKE t)
// ---------------------------------------------------------------------------

/// CREATE TABLE a (LIKE t) must be rejected.
///
/// This is safety-critical: SQLite parses LIKE as an ordinary identifier, so it
/// would silently create a table with a single column named LIKE of type t and
/// no columns from the referenced table. The translator must catch this before
/// emitting anything.
#[test]
fn like_clause_is_rejected() {
    let sql = "CREATE TABLE t (id INT); CREATE TABLE a (LIKE t);";
    let err = translate(sql).expect_err("LIKE clause must be rejected");
    let msg = err.to_string();
    // The message must name the construct and explain the risk.
    assert!(msg.contains("LIKE") || msg.contains("like"), "error must mention LIKE: {msg}");
}

// ---------------------------------------------------------------------------
// CREATE TABLE () INHERITS (t)
// ---------------------------------------------------------------------------

#[test]
fn inherits_is_rejected() {
    let sql = "CREATE TABLE t (id INT); CREATE TABLE a () INHERITS (t);";
    let err = translate(sql).expect_err("INHERITS must be rejected");
    let msg = err.to_string();
    assert!(
        msg.contains("INHERIT") || msg.contains("inherit"),
        "error must mention INHERITS: {msg}"
    );
}

// ---------------------------------------------------------------------------
// CREATE TABLE PARTITION OF
// ---------------------------------------------------------------------------

#[test]
fn partition_of_is_rejected() {
    let sql = "CREATE TABLE t (id INT, n INT) PARTITION BY RANGE (n); \
               CREATE TABLE a PARTITION OF t FOR VALUES FROM (1) TO (100);";
    let err = translate(sql).expect_err("PARTITION OF must be rejected");
    let msg = err.to_string();
    assert!(
        msg.contains("PARTITION") || msg.contains("partition"),
        "error must mention PARTITION OF: {msg}"
    );
}

// ---------------------------------------------------------------------------
// CREATE TABLE modifier leaks (R103)
// ---------------------------------------------------------------------------

/// `GLOBAL` and `LOCAL` are SQL-standard noise words PostgreSQL accepts and
/// ignores before `TEMPORARY`, measured on 16. Cleared with a warning, like
/// `UNLOGGED`, and the table stays temporary.
#[test]
fn global_and_local_temporary_are_cleared_with_a_warning() {
    for spelling in ["GLOBAL", "LOCAL"] {
        let (stmts, warnings) = translate_with_warnings(&format!(
            "CREATE {spelling} TEMPORARY TABLE t (id INT PRIMARY KEY);"
        ))
        .expect("a noise word must not fail the translation");
        assert!(
            stmts[0].contains("TEMPORARY") && !stmts[0].contains(spelling),
            "{spelling} must be cleared and TEMPORARY kept: {}",
            stmts[0]
        );
        assert!(!warnings.is_empty(), "clearing {spelling} must be reported");
        sqlite_accepts(&stmts).expect("the emitted DDL must run");
    }
}

/// The four foreign prefixes are refused naming the modifier, per the R13
/// rule, and so is a bare `GLOBAL` without `TEMPORARY`, which PostgreSQL
/// rejects too, measured on 16.
#[test]
fn foreign_create_table_modifiers_are_refused() {
    for (sql, modifier) in [
        ("CREATE OR REPLACE TABLE t (id INT PRIMARY KEY);", "OR REPLACE"),
        ("CREATE TRANSIENT TABLE t (id INT PRIMARY KEY);", "TRANSIENT"),
        ("CREATE VOLATILE TABLE t (id INT PRIMARY KEY);", "VOLATILE"),
        ("CREATE EXTERNAL TABLE t (id INT PRIMARY KEY);", "EXTERNAL"),
        ("CREATE GLOBAL TABLE t (id INT PRIMARY KEY);", "GLOBAL"),
    ] {
        let error = translate(sql).expect_err(modifier).to_string();
        assert!(error.contains(modifier), "the refusal must name the modifier {modifier}: {error}");
    }
}

/// `ON COMMIT PRESERVE ROWS` is PostgreSQL's own default for a temporary
/// table, and SQLite temporary tables already keep rows across transactions,
/// so clearing it is result-neutral and warned.
#[test]
fn on_commit_preserve_rows_is_cleared_with_a_warning() {
    let (stmts, warnings) = translate_with_warnings(
        "CREATE TEMPORARY TABLE t (id INT PRIMARY KEY) ON COMMIT PRESERVE ROWS;",
    )
    .expect("the default disposition must not fail the translation");
    assert!(!stmts[0].contains("ON COMMIT"), "the clause must be cleared: {}", stmts[0]);
    assert!(!warnings.is_empty(), "clearing ON COMMIT must be reported");
    sqlite_accepts(&stmts).expect("the emitted DDL must run");
}

/// `ON COMMIT DELETE ROWS` and `ON COMMIT DROP` change what a transaction
/// leaves behind, which SQLite cannot express, so both are refused.
#[test]
fn on_commit_that_changes_behaviour_is_refused() {
    for disposition in ["DELETE ROWS", "DROP"] {
        let error = translate(&format!(
            "CREATE TEMPORARY TABLE t (id INT PRIMARY KEY) ON COMMIT {disposition};"
        ))
        .expect_err(disposition)
        .to_string();
        assert!(
            error.contains("ON COMMIT"),
            "the refusal must name the clause for {disposition}: {error}"
        );
    }
}

/// PostgreSQL storage parameters, `WITH (fillfactor = 70)`, are performance
/// hints with no bearing on results, so they are cleared with a warning
/// rather than carried into SQLite, which answers `near "(": syntax error`.
#[test]
fn storage_parameters_are_cleared_with_a_warning() {
    let (stmts, warnings) =
        translate_with_warnings("CREATE TABLE t (id INT PRIMARY KEY) WITH (fillfactor = 70);")
            .expect("a storage parameter must not fail the translation");
    assert!(!stmts[0].contains("fillfactor"), "the parameter must be cleared: {}", stmts[0]);
    assert!(!warnings.is_empty(), "clearing a storage parameter must be reported");
    sqlite_accepts(&stmts).expect("the emitted DDL must run");
}

/// Guards the fix. Plain `TEMPORARY` and `IF NOT EXISTS` are legal in both
/// databases and must keep passing through untouched.
#[test]
fn temporary_and_if_not_exists_still_pass() {
    let stmts = translate("CREATE TEMPORARY TABLE IF NOT EXISTS t (id INT PRIMARY KEY);")
        .expect("both clauses are legal in both databases");
    assert!(
        stmts[0].contains("TEMPORARY") && stmts[0].contains("IF NOT EXISTS"),
        "both clauses must survive: {}",
        stmts[0]
    );
    sqlite_accepts(&stmts).expect("the emitted DDL must run");
}

// ---------------------------------------------------------------------------
// ALTER TABLE existence check (R104)
// ---------------------------------------------------------------------------

/// Before the fix the unguarded rename of an undeclared table emitted SQL
/// that SQLite refuses with `no such table`. It must be refused at
/// translation time like the other two operations.
#[test]
fn unguarded_rename_of_undeclared_table_is_refused() {
    let error = translate(
        "CREATE TABLE t (id INT PRIMARY KEY);\nALTER TABLE absent_table RENAME TO other;",
    )
    .expect_err("a rename of an undeclared table must not translate")
    .to_string();
    assert!(error.contains("absent_table"), "the refusal must name the table: {error}");
}

/// With or without `IF EXISTS`, the refusal is one message, not two dialects
/// of it.
#[test]
fn guarded_and_unguarded_rename_refusals_share_a_message() {
    let unguarded = translate(
        "CREATE TABLE t (id INT PRIMARY KEY);\nALTER TABLE absent_table RENAME TO other;",
    )
    .expect_err("unguarded rename of an undeclared table")
    .to_string();
    let guarded = translate(
        "CREATE TABLE t (id INT PRIMARY KEY);\nALTER TABLE IF EXISTS absent_table RENAME TO other;",
    )
    .expect_err("guarded rename of an undeclared table")
    .to_string();
    assert_eq!(unguarded, guarded);
}

/// All three SQLite-supported operations agree on refusing an undeclared
/// table. `ADD COLUMN` and `DROP COLUMN` already refuse from the schema
/// build, so this pins the agreement and that every refusal names the table.
#[test]
fn all_alter_operations_refuse_an_undeclared_table() {
    for operation in ["ADD COLUMN s TEXT", "DROP COLUMN s", "RENAME TO other"] {
        let error = translate(&format!(
            "CREATE TABLE t (id INT PRIMARY KEY);\nALTER TABLE absent_table {operation};"
        ))
        .expect_err(operation)
        .to_string();
        assert!(
            error.contains("absent_table"),
            "the refusal for {operation} must name the table: {error}"
        );
    }
}

/// Guards the fix. The snapshot keeps a renamed table under its declared
/// name, so a guarded rename of a table the batch declares must keep
/// translating, with the guard cleared for SQLite.
#[test]
fn guarded_rename_of_declared_table_still_translates() {
    let stmts =
        translate("CREATE TABLE t (id INT PRIMARY KEY);\nALTER TABLE IF EXISTS t RENAME TO t2;")
            .expect("a guarded rename of a declared table is valid in both databases");
    sqlite_accepts(&stmts).expect("the emitted DDL must run");
}

/// `CHECK ... NO INHERIT` parses since the sqlparser pin moved to `183e083e`.
/// The modifier only stops a constraint from reaching child tables, SQLite
/// has no table inheritance, and `INHERITS` is refused outright, so the CHECK
/// is kept, the modifier is dropped with a warning, and the emitted DDL runs.
#[test]
fn check_no_inherit_keeps_the_check_and_drops_the_modifier_with_a_warning() {
    for sql in [
        "CREATE TABLE t (id INT PRIMARY KEY, n INT, CHECK (n > 0) NO INHERIT);",
        "CREATE TABLE t (id INT PRIMARY KEY, n INT CHECK (n > 0) NO INHERIT);",
    ] {
        let (stmts, warnings) =
            translate_with_warnings(sql).expect("NO INHERIT must not fail the translation");
        assert!(
            stmts[0].contains("CHECK") && !stmts[0].contains("NO INHERIT"),
            "the CHECK must survive without the modifier: {}",
            stmts[0]
        );
        assert!(
            warnings.iter().any(|w| w.to_string().contains("NO INHERIT")),
            "dropping NO INHERIT must be reported: {warnings:?}"
        );
        sqlite_accepts(&stmts).expect("the emitted DDL must run");

        // The kept CHECK still enforces: an out-of-range row is refused.
        let conn = Connection::open_in_memory().unwrap();
        for stmt in &stmts {
            conn.execute_batch(stmt).unwrap();
        }
        conn.execute_batch("INSERT INTO t VALUES (1, 5);").expect("a passing row lands");
        let err = conn.execute_batch("INSERT INTO t VALUES (2, -1);");
        assert!(err.is_err(), "the CHECK must still enforce after the modifier is dropped");
    }
}
