//! Tests for function translation error cases.
//!
//! Verifies that PostgreSQL-specific functions that have no direct SQLite
//! equivalent produce clear, actionable error messages rather than silently
//! producing incorrect SQL.

use pg2sqlite::prelude::{Pg2Sqlite, Pg2SqliteOptions};

const SIMPLE_TABLE: &str = "CREATE TABLE t (id INT PRIMARY KEY, val INT, flag BOOLEAN);";

fn translate_err(sql: &str) -> String {
    Pg2Sqlite::default()
        .sql(sql)
        .unwrap()
        .translate(&Pg2SqliteOptions::default())
        .unwrap_err()
        .to_string()
}

// ---------------------------------------------------------------------------
// ts_rank / ts_rank_cd
// ---------------------------------------------------------------------------

/// `ts_rank` has no direct SQLite equivalent.  The translator should fail
/// with a message that directs the user to FTS5's `bm25()`.
#[test]
fn test_ts_rank_causes_error() {
    let sql = "
        CREATE TABLE documents (id INTEGER PRIMARY KEY, content TEXT);
        SELECT ts_rank(content, 'query') FROM documents;
    ";
    let result = Pg2Sqlite::default().sql(sql).unwrap().translate(&Pg2SqliteOptions::default());

    assert!(result.is_err(), "ts_rank should produce a translation error");
    let error_msg = result.unwrap_err().to_string();
    assert!(
        error_msg.contains("bm25"),
        "Error should mention 'bm25' as the FTS5 alternative, got: {error_msg}"
    );
}

/// `ts_rank_cd` is subject to the same restriction as `ts_rank`.
#[test]
fn test_ts_rank_cd_causes_error() {
    let sql = "
        CREATE TABLE documents (id INTEGER PRIMARY KEY, content TEXT);
        SELECT ts_rank_cd(content, 'query') FROM documents;
    ";
    let result = Pg2Sqlite::default().sql(sql).unwrap().translate(&Pg2SqliteOptions::default());

    assert!(result.is_err(), "ts_rank_cd should produce a translation error");
    let error_msg = result.unwrap_err().to_string();
    assert!(
        error_msg.contains("bm25"),
        "Error should mention 'bm25' as the FTS5 alternative, got: {error_msg}"
    );
}

// ---------------------------------------------------------------------------
// GENERATED BY DEFAULT AS IDENTITY
// ---------------------------------------------------------------------------

/// SQLite does not support `GENERATED BY DEFAULT AS IDENTITY`.  The translator
/// should return an explicit error rather than emitting invalid SQLite DDL.
#[test]
fn test_generated_by_default_as_identity_causes_error() {
    // PostgreSQL identity column with BY DEFAULT semantics
    let sql = "CREATE TABLE t (id INTEGER GENERATED BY DEFAULT AS IDENTITY, name TEXT NOT NULL);";
    let result = Pg2Sqlite::default().sql(sql).unwrap().translate(&Pg2SqliteOptions::default());

    assert!(result.is_err(), "GENERATED BY DEFAULT AS IDENTITY should produce a translation error");
    let error_msg = result.unwrap_err().to_string();
    assert!(
        error_msg.to_lowercase().contains("generated"),
        "Error should mention GENERATED, got: {error_msg}"
    );
}

// ---------------------------------------------------------------------------
// bool_and / bool_or / every
// ---------------------------------------------------------------------------

#[test]
fn bool_and_causes_error() {
    // bool_and has NULL semantics incompatible with MIN — must error, not silently
    // map.
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT bool_and(flag) FROM t;"));
    assert!(err.to_lowercase().contains("bool_and"), "Error must mention bool_and: {err}");
}

#[test]
fn bool_or_causes_error() {
    // bool_or has NULL semantics incompatible with MAX — must error, not silently
    // map.
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT bool_or(flag) FROM t;"));
    assert!(err.to_lowercase().contains("bool_or"), "Error must mention bool_or: {err}");
}

#[test]
fn every_causes_error() {
    // every is an alias for bool_and in PostgreSQL — must error, not silently map
    // to MIN.
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT every(flag) FROM t;"));
    assert!(
        err.to_lowercase().contains("every") || err.to_lowercase().contains("bool"),
        "Error must mention every or bool: {err}"
    );
}

// ---------------------------------------------------------------------------
// Statistical aggregates
// ---------------------------------------------------------------------------

#[test]
fn stddev_causes_error() {
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT stddev(val) FROM t;"));
    assert!(err.to_lowercase().contains("stddev"), "Error should mention stddev: {err}");
}

#[test]
fn stddev_pop_causes_error() {
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT stddev_pop(val) FROM t;"));
    assert!(err.to_lowercase().contains("stddev"), "Error should mention stddev: {err}");
}

#[test]
fn stddev_samp_causes_error() {
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT stddev_samp(val) FROM t;"));
    assert!(err.to_lowercase().contains("stddev"), "Error should mention stddev: {err}");
}

#[test]
fn variance_causes_error() {
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT variance(val) FROM t;"));
    assert!(err.to_lowercase().contains("variance"), "Error should mention variance: {err}");
}

#[test]
fn var_pop_causes_error() {
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT var_pop(val) FROM t;"));
    assert!(err.to_lowercase().contains("variance"), "Error should mention variance: {err}");
}

#[test]
fn var_samp_causes_error() {
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT var_samp(val) FROM t;"));
    assert!(err.to_lowercase().contains("variance"), "Error should mention variance: {err}");
}

#[test]
fn corr_causes_error() {
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT corr(id, val) FROM t;"));
    assert!(err.to_lowercase().contains("corr"), "Error should mention corr: {err}");
}

#[test]
fn covar_pop_causes_error() {
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT covar_pop(id, val) FROM t;"));
    assert!(err.to_lowercase().contains("covar"), "Error should mention covar: {err}");
}

#[test]
fn covar_samp_causes_error() {
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT covar_samp(id, val) FROM t;"));
    assert!(err.to_lowercase().contains("covar"), "Error should mention covar: {err}");
}

// ---------------------------------------------------------------------------
// bit_and / bit_or
// ---------------------------------------------------------------------------

#[test]
fn bit_and_causes_error() {
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT bit_and(val) FROM t;"));
    assert!(err.to_lowercase().contains("bit_and"), "Error should mention bit_and: {err}");
}

#[test]
fn bit_or_causes_error() {
    let err = translate_err(&format!("{SIMPLE_TABLE} SELECT bit_or(val) FROM t;"));
    assert!(err.to_lowercase().contains("bit_or"), "Error should mention bit_or: {err}");
}

// ---------------------------------------------------------------------------
// Sequence / utility functions → Unsupported
// ---------------------------------------------------------------------------

#[test]
fn currval_lastval_setval_unsupported() {
    for func in &["currval('seq')", "lastval()", "setval('seq', 1)"] {
        let sql = format!("SELECT {func};");
        let result =
            Pg2Sqlite::default().sql(&sql).unwrap().translate(&Pg2SqliteOptions::default());
        assert!(result.is_err(), "{func} should be unsupported: {result:?}");
    }
}

#[test]
fn repeat_unsupported() {
    let err = translate_err("SELECT repeat('ab', 3);");
    assert!(!err.is_empty(), "repeat should be unsupported");
}

#[test]
fn md5_unsupported() {
    let err = translate_err("SELECT md5('hello');");
    assert!(!err.is_empty(), "md5 should be unsupported");
}

#[test]
fn translate_function_unsupported() {
    let err = translate_err("SELECT translate('abc', 'a', 'x');");
    assert!(!err.is_empty(), "translate should be unsupported");
}

#[test]
fn to_date_unsupported() {
    let err = translate_err("SELECT to_date('2023-01-01', 'YYYY-MM-DD');");
    assert!(!err.is_empty(), "to_date should be unsupported");
}

#[test]
fn age_unsupported() {
    let err = translate_err("SELECT age(timestamp '2023-01-01');");
    assert!(!err.is_empty(), "age should be unsupported");
}

#[test]
fn regexp_match_unsupported() {
    let err = translate_err("SELECT regexp_match('abc', 'a');");
    assert!(!err.is_empty(), "regexp_match should be unsupported");
    let err2 = translate_err("SELECT regexp_matches('abc', 'a');");
    assert!(!err2.is_empty(), "regexp_matches should be unsupported");
}

#[test]
fn array_functions_unsupported() {
    let err = translate_err("SELECT array_length(ARRAY[1,2,3], 1);");
    assert!(!err.is_empty(), "array_length should be unsupported");
}

#[test]
fn format_unsupported() {
    let err = translate_err("SELECT format('Hello %s', 'world');");
    assert!(!err.is_empty(), "format should be unsupported");
}

// ---------------------------------------------------------------------------
// Negative tests from data type aliases
// ---------------------------------------------------------------------------

#[test]
fn percentile_cont_still_errors() {
    let err = translate_err("SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY val) FROM t;");
    assert!(!err.is_empty(), "Expected error for PERCENTILE_CONT, got empty");
}

#[test]
fn stddev_still_errors() {
    let err = translate_err("SELECT STDDEV(val) FROM t;");
    assert!(!err.is_empty(), "Expected error for STDDEV, got empty");
}

#[test]
fn regexp_replace_still_errors() {
    let err = translate_err("SELECT REGEXP_REPLACE(col, 'a', 'b') FROM t;");
    assert!(!err.is_empty(), "Expected error for REGEXP_REPLACE, got empty");
}

#[test]
fn split_part_still_errors() {
    let err = translate_err("SELECT SPLIT_PART(col, ',', 1) FROM t;");
    assert!(!err.is_empty(), "Expected error for SPLIT_PART, got empty");
}
