//! Focused tests for DDL clause gap fixes: ALTER TABLE RENAME, GENERATED AS
//! IDENTITY, CREATE UNLOGGED TABLE, and LIKE/INHERITS/PARTITION OF rejects.
//!
//! These tests assert observable contracts (exact emitted SQL or error message
//! content) rather than implementation internals.

use pg2sqlite::{
    prelude::{Pg2Sqlite, Pg2SqliteOptions},
    warnings::TranslationWarning,
};
use rusqlite::Connection;

fn opts() -> Pg2SqliteOptions {
    Pg2SqliteOptions::default()
}

/// Translates `sql` with the given options and returns the string vec.
fn translate(sql: &str) -> Result<Vec<String>, pg2sqlite::errors::Error> {
    Pg2Sqlite::default().sql(sql)?.translate_to_sql(&opts())
}

/// Translates `sql` and collects warnings alongside the string vec.
fn translate_with_warnings(
    sql: &str,
) -> Result<(Vec<String>, Vec<TranslationWarning>), pg2sqlite::errors::Error> {
    let report = Pg2Sqlite::default().sql(sql)?.translate_with_report(&opts())?;
    let stmts = report.statements.iter().map(|s| s.to_string()).collect();
    Ok((stmts, report.warnings))
}

/// Executes every statement in `stmts` through rusqlite to confirm they parse
/// and run without error.
///
/// # Errors
///
/// Returns the first SQLite error encountered.
fn sqlite_accepts(stmts: &[String]) -> Result<(), rusqlite::Error> {
    let conn = Connection::open_in_memory()?;
    for s in stmts {
        conn.execute_batch(s)?;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// ALTER TABLE RENAME TO
// ---------------------------------------------------------------------------

/// Before the fix this panicked inside sql-traits schema construction, which is
/// a public-API defect. After the fix it must return Ok and the emitted SQL
/// must be valid SQLite.
#[test]
fn rename_no_longer_panics() {
    let setup = "CREATE TABLE t (id INT PRIMARY KEY);";
    let rename = "ALTER TABLE t RENAME TO t2;";
    let full = format!("{setup}\n{rename}");

    // Must not panic.
    let result = std::panic::catch_unwind(|| translate(&full));
    let stmts = result.expect("translate must not panic").expect("translate must succeed");

    // The last statement must be the rename, and it must run without error.
    let rename_stmt = stmts.last().expect("at least one statement emitted");
    assert!(
        rename_stmt.to_uppercase().contains("RENAME"),
        "expected RENAME in emitted statement, got: {rename_stmt}"
    );

    // Build a fresh db with the original table, then apply the rename.
    let conn = Connection::open_in_memory().unwrap();
    conn.execute_batch("CREATE TABLE t (id INTEGER PRIMARY KEY NOT NULL) STRICT;").unwrap();
    conn.execute_batch(rename_stmt).unwrap();
}

// ---------------------------------------------------------------------------
// GENERATED AS IDENTITY on an integer primary key
// ---------------------------------------------------------------------------

/// GENERATED ALWAYS AS IDENTITY on INTEGER PRIMARY KEY must produce the same
/// output as the equivalent SERIAL column, because SQLite's INTEGER PRIMARY KEY
/// is a rowid alias that already auto-assigns.
#[test]
fn identity_always_pk_equals_serial() {
    let identity_sql = "CREATE TABLE a (id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY);";
    let serial_sql = "CREATE TABLE a (id SERIAL PRIMARY KEY);";

    let identity_out = translate(identity_sql).expect("identity should translate");
    let serial_out = translate(serial_sql).expect("serial should translate");

    assert_eq!(
        identity_out, serial_out,
        "GENERATED ALWAYS AS IDENTITY on INTEGER PRIMARY KEY must match SERIAL output"
    );

    sqlite_accepts(&identity_out).expect("emitted SQL must be valid SQLite");
}

/// GENERATED BY DEFAULT AS IDENTITY on INTEGER PRIMARY KEY must also succeed
/// and match the SERIAL output.
#[test]
fn identity_by_default_pk_equals_serial() {
    let identity_sql = "CREATE TABLE a (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);";
    let serial_sql = "CREATE TABLE a (id SERIAL PRIMARY KEY);";

    let identity_out = translate(identity_sql).expect("identity should translate");
    let serial_out = translate(serial_sql).expect("serial should translate");

    assert_eq!(
        identity_out, serial_out,
        "GENERATED BY DEFAULT AS IDENTITY on INTEGER PRIMARY KEY must match SERIAL output"
    );
}

/// An integer primary key translated from an IDENTITY column must actually
/// auto-assign when a row is inserted without providing that column.
#[test]
fn identity_pk_auto_assigns_on_insert() {
    let sql = "CREATE TABLE a (id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY);";
    let stmts = translate(sql).expect("should translate");
    sqlite_accepts(&stmts).expect("DDL must be valid");

    let conn = Connection::open_in_memory().unwrap();
    for s in &stmts {
        conn.execute_batch(s).unwrap();
    }
    conn.execute_batch("INSERT INTO a DEFAULT VALUES;").unwrap();
    let id: i64 = conn.query_row("SELECT id FROM a", [], |row| row.get(0)).unwrap();
    assert_ne!(id, 0, "auto-assigned rowid must be nonzero");
}

/// GENERATED AS IDENTITY on a non-integer-primary-key column must be rejected.
/// SQLite can only auto-assign the rowid (INTEGER PRIMARY KEY).
#[test]
fn identity_non_pk_is_rejected() {
    let sql = "CREATE TABLE a (id INT, x INT GENERATED ALWAYS AS IDENTITY);";
    let err = translate(sql).expect_err("non-PK IDENTITY must be an error");
    let msg = err.to_string();
    assert!(
        msg.contains("IDENTITY") || msg.contains("identity") || msg.contains("INTEGER PRIMARY KEY"),
        "error must name the construct and why it fails: {msg}"
    );
}

/// GENERATED BY DEFAULT AS IDENTITY on a non-PK column must also be rejected.
#[test]
fn identity_by_default_non_pk_is_rejected() {
    let sql = "CREATE TABLE a (id INT PRIMARY KEY, x INT GENERATED BY DEFAULT AS IDENTITY);";
    let err = translate(sql).expect_err("non-PK BY DEFAULT IDENTITY must be an error");
    let msg = err.to_string();
    assert!(
        msg.contains("IDENTITY") || msg.contains("identity") || msg.contains("INTEGER PRIMARY KEY"),
        "error must name the construct and why it fails: {msg}"
    );
}

// ---------------------------------------------------------------------------
// CREATE UNLOGGED TABLE
// ---------------------------------------------------------------------------

/// UNLOGGED must be stripped and the table must be emitted as a normal table.
/// A LossyDrop warning must be emitted.
#[test]
fn unlogged_drops_modifier_and_warns() {
    let sql = "CREATE UNLOGGED TABLE a (id INT PRIMARY KEY);";
    let (stmts, warnings) = translate_with_warnings(sql).expect("UNLOGGED should translate");

    // The emitted SQL must not contain UNLOGGED.
    for s in &stmts {
        assert!(
            !s.to_uppercase().contains("UNLOGGED"),
            "emitted SQL must not contain UNLOGGED: {s}"
        );
    }

    // The table must be valid SQLite.
    sqlite_accepts(&stmts).expect("emitted SQL must be valid SQLite");

    // A LossyDrop warning must have been emitted for the UNLOGGED modifier.
    let has_warning = warnings.iter().any(|w| {
        matches!(w, TranslationWarning::LossyDrop { construct, .. } if *construct == "UNLOGGED")
    });
    assert!(has_warning, "expected a LossyDrop warning for UNLOGGED, got: {warnings:?}");
}

// ---------------------------------------------------------------------------
// CREATE TABLE (LIKE t)
// ---------------------------------------------------------------------------

/// CREATE TABLE a (LIKE t) must be rejected.
///
/// This is safety-critical: SQLite parses LIKE as an ordinary identifier, so it
/// would silently create a table with a single column named LIKE of type t and
/// no columns from the referenced table. The translator must catch this before
/// emitting anything.
#[test]
fn like_clause_is_rejected() {
    let sql = "CREATE TABLE t (id INT); CREATE TABLE a (LIKE t);";
    let err = translate(sql).expect_err("LIKE clause must be rejected");
    let msg = err.to_string();
    // The message must name the construct and explain the risk.
    assert!(msg.contains("LIKE") || msg.contains("like"), "error must mention LIKE: {msg}");
}

// ---------------------------------------------------------------------------
// CREATE TABLE () INHERITS (t)
// ---------------------------------------------------------------------------

#[test]
fn inherits_is_rejected() {
    let sql = "CREATE TABLE t (id INT); CREATE TABLE a () INHERITS (t);";
    let err = translate(sql).expect_err("INHERITS must be rejected");
    let msg = err.to_string();
    assert!(
        msg.contains("INHERIT") || msg.contains("inherit"),
        "error must mention INHERITS: {msg}"
    );
}

// ---------------------------------------------------------------------------
// CREATE TABLE PARTITION OF
// ---------------------------------------------------------------------------

#[test]
fn partition_of_is_rejected() {
    let sql = "CREATE TABLE t (id INT, n INT) PARTITION BY RANGE (n); \
               CREATE TABLE a PARTITION OF t FOR VALUES FROM (1) TO (100);";
    let err = translate(sql).expect_err("PARTITION OF must be rejected");
    let msg = err.to_string();
    assert!(
        msg.contains("PARTITION") || msg.contains("partition"),
        "error must mention PARTITION OF: {msg}"
    );
}
