//! What a generated key answers, against what a PostgreSQL sequence answers.
//!
//! A `SERIAL` or `IDENTITY` column becomes SQLite's rowid alias. A bare rowid
//! hands out `max(rowid) + 1`, so it re-uses the key of a deleted row, where a
//! PostgreSQL sequence never looks back. `AUTOINCREMENT` keeps the high-water
//! mark and answers what PostgreSQL answers, measured on PostgreSQL 17.
//!
//! Two divergences are inherent to a rowid and are not fixed here: an explicit
//! value moves the counter, where PostgreSQL leaves its sequence alone, and a
//! failed insert consumes no value, where PostgreSQL's sequence has already
//! advanced.

use pg2sqlite::{
    prelude::{Pg2Sqlite, Pg2SqliteOptions},
    warnings::TranslationWarning,
};
use rusqlite::Connection;

/// Applies the translated `ddl`, runs each of `writes`, and returns the `id`
/// values in ascending order.
///
/// # Panics
///
/// Panics when translation fails or when an emitted statement will not
/// execute. A write that SQLite rejects is recorded rather than fatal, since
/// which writes are refused is what several tests are about.
fn ids_after(ddl: &str, writes: &[&str]) -> Vec<i64> {
    let statements = Pg2Sqlite::default()
        .sql(ddl)
        .expect("fixture parses")
        .translate_to_sql(&Pg2SqliteOptions::default())
        .expect("fixture translates");

    let connection = Connection::open_in_memory().expect("in-memory SQLite");
    for statement in &statements {
        connection
            .execute_batch(&format!("{statement};"))
            .unwrap_or_else(|error| panic!("emitted statement failed: {error}\n{statement}"));
    }
    for write in writes {
        let _ = connection.execute_batch(&format!("{write};"));
    }

    let mut prepared = connection.prepare("SELECT id FROM t ORDER BY id").expect("probe prepares");
    prepared
        .query_map([], |row| row.get::<_, i64>(0))
        .expect("probe runs")
        .collect::<Result<Vec<_>, _>>()
        .expect("probe rows decode")
}

/// Translating `sql` and expecting a refusal, returned as its message.
///
/// # Panics
///
/// Panics when the input parses and translates, which is the defect these
/// tests pin.
fn refusal(sql: &str) -> String {
    Pg2Sqlite::default()
        .sql(sql)
        .expect("fixture parses")
        .translate(&Pg2SqliteOptions::default())
        .expect_err("expected a refusal")
        .to_string()
}

const SERIAL: &str = "CREATE TABLE t (id SERIAL PRIMARY KEY, n INT NOT NULL);";

/// PostgreSQL answers `1, 3`: the sequence does not hand out `2` again.
#[test]
fn a_deleted_key_is_not_handed_out_again() {
    assert_eq!(
        ids_after(
            SERIAL,
            &[
                "INSERT INTO t (n) VALUES (1)",
                "INSERT INTO t (n) VALUES (2)",
                "DELETE FROM t WHERE id = 2",
                "INSERT INTO t (n) VALUES (3)",
            ],
        ),
        vec![1, 3]
    );
}

/// The same for `GENERATED BY DEFAULT AS IDENTITY`, which is the spelling
/// PostgreSQL recommends over `SERIAL`.
#[test]
fn an_identity_column_does_not_hand_out_a_deleted_key_again() {
    assert_eq!(
        ids_after(
            "CREATE TABLE t (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, n INT NOT NULL);",
            &[
                "INSERT INTO t (n) VALUES (1)",
                "INSERT INTO t (n) VALUES (2)",
                "DELETE FROM t WHERE id = 2",
                "INSERT INTO t (n) VALUES (3)",
            ],
        ),
        vec![1, 3]
    );
}

/// Keys still start at one and count up when nothing is deleted.
#[test]
fn a_generated_key_still_counts_up_from_one() {
    assert_eq!(
        ids_after(SERIAL, &["INSERT INTO t (n) VALUES (1)", "INSERT INTO t (n) VALUES (2)"]),
        vec![1, 2]
    );
}

/// `GENERATED BY DEFAULT` takes an explicit value, as PostgreSQL does.
#[test]
fn generated_by_default_takes_an_explicit_value() {
    assert_eq!(
        ids_after(
            "CREATE TABLE t (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, n INT NOT NULL);",
            &["INSERT INTO t (id, n) VALUES (10, 1)"],
        ),
        vec![10]
    );
}

/// PostgreSQL refuses an explicit value for `GENERATED ALWAYS AS IDENTITY`
/// with `cannot insert a non-DEFAULT value into column "id"`, and the emitted
/// schema has no way to tell an omitted column from a supplied one at run
/// time, so the statement is refused where it is translated.
#[test]
fn generated_always_refuses_an_explicit_value() {
    let message = refusal(
        "CREATE TABLE t (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, n INT NOT NULL);
         INSERT INTO t (id, n) VALUES (10, 1);",
    );
    assert!(message.contains("id"), "{message}");
    assert!(message.to_lowercase().contains("identity"), "{message}");
}

/// The same column still takes an insert that leaves the key to the database.
#[test]
fn generated_always_takes_an_insert_without_the_key() {
    assert_eq!(
        ids_after(
            "CREATE TABLE t (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, n INT NOT NULL);",
            &["INSERT INTO t (n) VALUES (1)", "INSERT INTO t (n) VALUES (2)"],
        ),
        vec![1, 2]
    );
}

/// A `DEFAULT` written for the key is PostgreSQL's own way of asking for the
/// generated value, so it must translate and land a generated key, where an
/// explicit value is refused.
#[test]
fn generated_always_takes_the_default_keyword() {
    assert_eq!(
        ids_after(
            "CREATE TABLE t (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, n INT NOT NULL);
             INSERT INTO t (id, n) VALUES (DEFAULT, 1);",
            &[],
        ),
        vec![1]
    );
}

/// The key can be declared as a table constraint instead of inline, and the
/// sequence has to behave the same way. SQLite takes `AUTOINCREMENT` only
/// beside a column-level `PRIMARY KEY`, so the constraint is folded into the
/// column it names.
#[test]
fn a_table_level_primary_key_over_the_identity_column_keeps_the_high_water_mark() {
    assert_eq!(
        ids_after(
            "CREATE TABLE t (id SERIAL, n INT NOT NULL, PRIMARY KEY (id));",
            &[
                "INSERT INTO t (n) VALUES (1)",
                "INSERT INTO t (n) VALUES (2)",
                "DELETE FROM t WHERE id = 2",
                "INSERT INTO t (n) VALUES (3)",
            ],
        ),
        vec![1, 3]
    );
}

/// A named constraint keeps its name once it moves onto the column, since
/// SQLite takes `CONSTRAINT <name> PRIMARY KEY` there too.
#[test]
fn a_named_table_level_primary_key_keeps_its_name() {
    let statements = Pg2Sqlite::default()
        .sql("CREATE TABLE t (id SERIAL, n INT, CONSTRAINT t_pkey PRIMARY KEY (id));")
        .expect("fixture parses")
        .translate_to_sql(&Pg2SqliteOptions::default())
        .expect("fixture translates");
    let ddl = statements.join("\n");
    assert!(ddl.contains("CONSTRAINT t_pkey PRIMARY KEY AUTOINCREMENT"), "{ddl}");

    let connection = Connection::open_in_memory().expect("in-memory SQLite");
    // The translator leads with a dialect pragma; execute each statement
    // individually.
    for stmt in &statements {
        connection.execute_batch(&format!("{stmt};")).expect("emitted DDL executes");
    }
}

/// A composite key is not the rowid, so nothing is folded and the column
/// keeps whatever the rest of the translation gives it.
#[test]
fn a_composite_primary_key_over_the_identity_column_is_refused() {
    let message = refusal("CREATE TABLE t (id SERIAL, n INT NOT NULL, PRIMARY KEY (id, n));");
    assert!(message.contains("id"), "{message}");
}

/// The same refusal when the value comes from a query rather than a row,
/// where the statement cannot be inspected value by value.
#[test]
fn generated_always_refuses_a_value_from_a_query() {
    let message = refusal(
        "CREATE TABLE t (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, n INT NOT NULL);
         CREATE TABLE s (k INT NOT NULL, m INT NOT NULL);
         INSERT INTO t (id, n) SELECT k, m FROM s;",
    );
    assert!(message.contains("id"), "{message}");
    assert!(message.to_lowercase().contains("identity"), "{message}");
}

/// A multi-row insert is refused on whichever row supplies the key, since the
/// column list is shared by every row.
#[test]
fn generated_always_refuses_a_later_row_that_supplies_the_key() {
    let message = refusal(
        "CREATE TABLE t (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, n INT NOT NULL);
         INSERT INTO t (id, n) VALUES (DEFAULT, 1), (7, 2);",
    );
    assert!(message.contains('7'), "{message}");
}

/// Two divergences a rowid cannot close are reported rather than hidden: a
/// supplied value moves the counter, where a PostgreSQL sequence is untouched
/// by one, and a failed insert consumes no value, where a sequence has
/// already advanced.
#[test]
fn a_generated_key_reports_what_a_rowid_cannot_promise() {
    let warnings = Pg2Sqlite::default()
        .sql(SERIAL)
        .expect("fixture parses")
        .translate_with_report(&Pg2SqliteOptions::default())
        .expect("fixture translates")
        .warnings;
    let reasons: Vec<String> = warnings
        .iter()
        .filter_map(|warning| {
            match warning {
                TranslationWarning::LossyDowngrade { construct, location, reason, .. }
                    if construct == "SERIAL" =>
                {
                    Some(format!("{location}: {reason}"))
                }
                _ => None,
            }
        })
        .collect();
    assert_eq!(reasons.len(), 1, "{warnings:?}");
    assert!(reasons[0].contains("t.id"), "{reasons:?}");
    assert!(reasons[0].contains("rolled back"), "{reasons:?}");
}

/// PostgreSQL 17 answers `column "id" can only be updated to DEFAULT` for an
/// `UPDATE` that writes a value into a `GENERATED ALWAYS AS IDENTITY` column,
/// so the statement is refused rather than emitted as a plain assignment.
#[test]
fn generated_always_refuses_an_update_of_the_key() {
    let message = refusal(
        "CREATE TABLE t (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, n INT NOT NULL);
         UPDATE t SET id = 5;",
    );
    assert!(message.contains("id"), "{message}");
    assert!(message.to_lowercase().contains("identity"), "{message}");
}

/// `UPDATE t SET id = DEFAULT` takes the next sequence value in PostgreSQL,
/// measured as `1` becoming `2`. SQLite has no such value to reach for in an
/// `UPDATE`, and the assignment was emitted as `id = NULL`, which SQLite
/// answers `datatype mismatch` for on a rowid alias, so it is refused.
#[test]
fn a_generated_key_refuses_an_update_to_default() {
    let message = refusal(
        "CREATE TABLE t (id SERIAL PRIMARY KEY, n INT NOT NULL);
         UPDATE t SET id = DEFAULT;",
    );
    assert!(message.contains("id"), "{message}");
    assert!(message.contains("DEFAULT"), "{message}");
}

/// A plain column still takes `DEFAULT` in an `UPDATE`, which is what the
/// substitution is for.
#[test]
fn a_plain_column_still_takes_an_update_to_default() {
    assert_eq!(
        ids_after(
            "CREATE TABLE t (id SERIAL PRIMARY KEY, n INT NOT NULL DEFAULT 7);
             INSERT INTO t (n) VALUES (1);
             UPDATE t SET n = DEFAULT;",
            &[],
        ),
        vec![1]
    );
}

/// A key that PostgreSQL lets a caller write is still writable, since
/// `GENERATED BY DEFAULT` and `SERIAL` both take an explicit value.
#[test]
fn generated_by_default_takes_an_update_of_the_key() {
    assert_eq!(
        ids_after(
            "CREATE TABLE t (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, n INT NOT NULL);
             INSERT INTO t (n) VALUES (1);
             UPDATE t SET id = 5;",
            &[],
        ),
        vec![5]
    );
}
