//! Shared test helpers for pg2sqlite integration tests.

use diesel::{prelude::*, sqlite::SqliteConnection};
use uuid::Uuid;

/// Implementation of UUIDv7 generation for SQLite.
pub fn uuidv7_impl() -> Vec<u8> {
    let utc_now = chrono::Utc::now();
    let seconds = u64::try_from(utc_now.timestamp()).expect("Went back in time");
    let subsec_nanos = utc_now.timestamp_subsec_nanos();
    let counter = 0;
    let usable_counter_bits = 12;
    let timestamp =
        uuid::Timestamp::from_unix_time(seconds, subsec_nanos, counter, usable_counter_bits);
    Uuid::new_v7(timestamp).as_bytes().to_vec()
}

/// Establishes an in-memory SQLite connection with:
/// - Foreign keys enabled
/// - Recursive triggers enabled
///
/// Note: The caller must register the uuidv7 function after calling this,
/// using the `uuidv7_utils` module generated by `#[declare_sql_function]`.
pub fn establish_connection_base() -> SqliteConnection {
    let mut connection =
        SqliteConnection::establish(":memory:").expect("Error connecting to in-memory SQLite");

    diesel::sql_query("PRAGMA foreign_keys = ON")
        .execute(&mut connection)
        .expect("Failed to enable foreign key constraints");

    diesel::sql_query("PRAGMA recursive_triggers = ON")
        .execute(&mut connection)
        .expect("Failed to enable recursive triggers");

    connection
}

/// Common query result type for counting rows.
#[derive(QueryableByName, Debug)]
pub struct Count {
    #[diesel(sql_type = diesel::sql_types::BigInt)]
    pub count: i64,
}

/// Common query result type for UUID id fields.
#[allow(dead_code)]
#[derive(QueryableByName, Debug)]
pub struct IdResult {
    #[diesel(sql_type = diesel::sql_types::Binary)]
    pub id: Vec<u8>,
}
